apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: notsentinal
spec:
  kubeConfig:
    secretRef:
      name: demo1-stage-kubeconfig
  targetNamespace: default
  storageNamespace: default
