---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: notsentinal
spec:
  releaseName: notsentinal
  chart:
    spec:
      chart: airflow
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 10m
  install:
    remediation:
      retries: 3
  values: {}
